#!/bin/zsh
[[ -x =rename ]] || {zenity --error --text "rename is not installed"; exit 1}
local PR_EXPR="$(zenity --title="rename arguments" --entry --entry-text='s///')"

fp=(${(f)NAUTILUS_SCRIPT_SELECTED_FILE_PATHS})
rename -e "${PR_EXPR}" "${fp[@]:t}"
