#!/bin/zsh
[[ -x =pdf180 ]] || { MSG="Please install pdfjam which comes with texlive-extra-utils to modify PDFs"; echo $MSG; zenity --info --text="$MSG" --icon-name=error  ;exit 1}
[[ -n ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS} ]] && FILES=(${(f)NAUTILUS_SCRIPT_SELECTED_FILE_PATHS})
[[ ${#FILES} -eq 0 ]] && FILES=("$@")

pdf180 --suffix 'upturned' --batch "${FILES[@]}"
