#!/bin/zsh
[[ -n ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS} ]] && FILES=(${(f)NAUTILUS_SCRIPT_SELECTED_FILE_PATHS})
[[ ${#FILES} -eq 0 ]] && FILES=("$@")
for f in "${FILES[@]}" ; do
  ${0:h}/../.helpers/shrinkpdf.sh "$f" "${f:r}.shrinked.${f:e}" 150
done
