#!/bin/zsh
[[ -x =gs ]] || { MSG="Please install ghostscript to shrink PDFs"; echo $MSG; zenity --info --text="$MSG" --icon-name=error  ;exit 1}
[[ -n ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS} ]] && FILES=(${(f)NAUTILUS_SCRIPT_SELECTED_FILE_PATHS})
[[ ${#FILES} -eq 0 ]] && FILES=("$@")
for f in "${FILES[@]}" ; do
  ${0:h}/../.helpers/shrinkpdf.sh "$f" "${f:r}.shrinked.${f:e}" 150
done
