#!/bin/zsh

local dir
if [[ -z $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ]]; then
  base=$(echo "$NAUTILUS_SCRIPT_CURRENT_URI" | cut -d'/' -f3-)  #remove file://
  base_stripped="$(printf -v base "%b" "${base/\%/\x}")"
  dir="$base_stripped"
else
  for fp in ${(f)NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}; do
    if [[ -d $fp ]]; then
      dir=${fp}
      break
    elif [[ -f $fp ]]; then
      dir=${fp:h}
      break        
    fi
  done
fi

[[ -n $dir ]] && ~/.local/share/nautilus/scripts/.helpers/guake_cd_to.sh "$dir"
