#!/bin/bash
echo -e "NAUTILUS_SCRIPT_SELECTED_FILE_PATHS: $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS\n \
NAUTILUS_SCRIPT_SELECTED_URIS: $NAUTILUS_SCRIPT_SELECTED_URIS\n \
NAUTILUS_SCRIPT_CURRENT_URI: $NAUTILUS_SCRIPT_CURRENT_URI\n \
NAUTILUS_SCRIPT_WINDOW_GEOMETRY: $NAUTILUS_SCRIPT_WINDOW_GEOMETRY \ņ\n \
ARGS: $* \n\n \
PWD: $PWD" |  zenity --text-info
