#!/bin/zsh
type ffmpeg || exit 1
local extra_options=($(echo -e '-c:v hevc_cuvid -resize 2880x1600\nresize t0 2880x1600' | zenity --width=1400 --height=600 --list --title "Choose ffmpeg filter" --multiple --column "args to add" --column "description" --print-column=1 --separator=' ' --editable))
(
for mp4 in "${(f)NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}"; do
  [[ ${mp4:e:l} != mp4 && ${mp4:e:l} != mts ]] && continue
  local dst="${mp4:r}".hevc_nvenc_filter_applied.mp4
  [[ -e $dst ]] && continue
  #ffmpeg -strict 2 -hwaccel auto -i "$mp4" -c:v h264_cuvid -c:a copy –vf scale_npp=2880:-1:interp_algo=super -c:v hevc_nvenc -rc vbr_hq -cq 25 -profile:v main10 -pix_fmt p010le -b:v 0K -c:a copy -map 0 "$dst" \
  #ffmpeg -strict 2 -hwaccel auto -c:v h264_cuvid -i "$mp4"  -vf scale_npp=2880:1600:interp_algo=super -c:v hevc_nvenc -rc vbr_hq -cq 25 -profile:v main10 -pix_fmt p010le -b:v 0K -c:a copy -map 0 "$dst" \
  ffmpeg -vsync 0 -strict 2 -hwaccel auto $extra_options -i "$mp4" -c:v hevc_nvenc -rc vbr_hq -cq 25 -profile:v main10 -pix_fmt p010le -b:v 0K -c:a copy -map 0 "$dst"  \
    && exiftool -overwrite_original -extractEmbedded -TagsFromFile "$mp4" "$dst" && touch -r "$mp4" "$dst" || rm "$dst"
  ## if file hast 0 bytes, remove it
  [[ -f "$dst" && ! -s "$dst" ]] && rm "$dst"
done
) |& zenity --text-info --no-interaction --text "${mp4:t} -> ${dst:t}" --title "ffmpeg transcoding" --auto-scroll --width 1024 --height 640
exit 0

