#!/bin/zsh
type ffmpeg || exit 1
local extra_options=($(echo -e '-vf transpose=0\nRotate 90°CCW and flip vertically\n-vf transpose=3\nRotate 90°CW and flip vertically\n-vf transpose=1\nRotate 90° CW\n-vf transpose=2\nRotate 90° CCW\n-vf transpose=2,transpose=2\nRotate 180°\n-vf lutyuv=y=val*4\nBrighten by factor 4\n-vf lutyuv=y=gammaval(0.7)\nincrease gamma by 30%?\n-vf lutyuv=y=gammaval(0.2)\nincrease gamma by 5\n-vf scale=1920:-1\nScale to 1920 and keep aspect ratio\n-vf unsharp=9:9:1.5:9:9:1.5\nSharpen Video\n-filter_complex [0:v]trim=start=0:duration=25[adark];[0:v]trim=start=25:duration=385,setpts=PTS-STARTPTS[bok];[adark]lutyuv=y=gammaval(0.7)[abrighter];[abrighter][bok]concat[out1] -map [out1]:v:0 -map 0:a:0 -map\nGamma increase first 25s of video' | zenity --width=1400 --height=600 --list --title "Choose ffmpeg filter" --multiple --column "args to add" --column "description" --print-column=1 --separator=' ' --editable))
(
for mp4 in "${(f)NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}"; do
  [[ ${mp4:e:l} != mp4 && ${mp4:e:l} != mts ]] && continue
  local dst="${mp4:r}".x265_filter_applied.mp4
  [[ -e $dst ]] && continue
  ffmpeg -i "$mp4" -c:a copy -movflags use_metadata_tags -map_metadata 0 $extra_options -vcodec libx265 -crf 25 "$dst" \
    && exiftool -overwrite_original -extractEmbedded -TagsFromFile "$mp4" "$dst" && touch -r "$mp4" "$dst" || rm "$dst"
  ## if file hast 0 bytes, remove it
  [[ -f "$dst" && ! -s "$dst" ]] && rm "$dst"
done
) |& zenity --text-info --no-interaction --text "${mp4:t} -> ${dst:t}" --title "ffmpeg transcoding" --auto-scroll --width 1024 --height 640
exit 0

