#!/bin/bash
IFS=$'\n'
DF=$(mktemp)
for picture in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
	png_file=`echo "$picture" | sed 's/\.\w*$/.png/'`
  touch -m -c -r "$picture" $DF
	/usr/bin/convert "$picture" png:"$png_file"
  touch -m -c -r $DF "$png_file"  ## two-step touch in case original picture also has jpg extension even tough it is another format
done
rm "$DF"
