#!/bin/zsh
setopt extendedglob braceccl globcomplete histsubstpattern
local destdir="$PWD"
local -a selected_paths
local last_x_days=$(zenity --title="Copy new photos here" --text="last x days of images" --entry --entry-text='1')
last_x_days=$(($last_x_days))
selected_paths=(${(f)NAUTILUS_SCRIPT_SELECTED_FILE_PATHS})
[[ ${#selected_paths} -eq 1 && -d ${selected_paths[1]} ]] && destdir="${selected_paths[1]}"

local MSG="$(~/copy_new_photos.sh $last_x_days "$destdir")"
if [[ $? -eq 0 ]]; then
	notify-send --hint=int:transient:0 -u low -t 5 "Finished copying new images"
else
	notify-send --hint=int:transient:0 -u low -t 5 "$MSG"
fi
