#!/bin/zsh
[[ -x =exiftool ]] || {zenity --error --text "exiftool is not installed"; exit 1}
[[ -n ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS} ]] && FILES=(${(f)NAUTILUS_SCRIPT_SELECTED_FILE_PATHS})
[[ ${#FILES} -eq 0 ]] && FILES=("$@")
[[ ${#FILES} -gt 1 ]] && local common_files_prefix="$(print -l "${FILES[@]:t}" |sed -e '$!{N;s/^\(.*\).*\n\1.*$/\1\n\1/;D;}' | sed 's/\s\([0-9-]\+\s\?\([0-9hm]\+\s*\)\?\)\?$//')"
local default_prepend="Overall Context"
local default_append='Taken Where'
local default_append2='Taken By Whom'
img_prepend="$(zenity --title="Prepend context to filename" --entry --entry-text="${common_files_prefix:-$default_prepend}")" || exit 1
img_append="$(zenity --title="Append to filename" --entry --entry-text="$default_append")" || exit 1
img_append2="$(zenity --title="Append fotographer to filename" --entry --entry-text="$default_append2")" || exit 1
[[ $img_prepend == $default_prepend ]] && img_prepend=""
[[ $img_append == $default_append ]] && img_append=""
[[ $img_append2 == $default_append2 ]] && img_append2=""
[[ -n $img_prepend && $img_prepend[-1] != " " ]] && img_prepend="$img_prepend "
[[ -n $img_append && $img_append[0] != " " ]] && img_append=" $img_append"
[[ -n $img_append2 && $img_append2[0] != " " ]] && img_append="$img_append by $img_append2"

## last -FileName assignment superseedes the earlier one if all variables are defined
exiftool -m '-DateTimeOriginal>FileModifyDate' -if '$CreateDate' '-FileName<${CreateDate}${model;s/^/ /}.%e' -d "${img_prepend}%Y-%m-%d %Hh%Mm%S%%-c${img_append}" "${FILES[@]}"
