#!/bin/zsh
[[ -x =exiftool ]] || {zenity --error --text "exiftool is not installed"; exit 1}
exiftool -api largefilesupport=1 -overwrite_original -api QuickTimeUTC -AllDates'<'FileModifyDate -m -P "${(f)NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}"
